version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scrapy:
    build:
      context: ./scrappy
    volumes:
      - ./scrappy:/app
    depends_on:
      - postgres

  app:
    build: 
        context: ./app
    ports:
      - "8080:8080"

volumes:
  postgres_data:
