version: '3'
services:
  postgres:
    build:
        context: ./db
    ports:
        - "5432:5432"

  scrapy:
    build:
      context: ./scrappy
    depends_on:
      - postgres

  app:
    build: 
        context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
